### ISSUE TITLE
Redundant appendage of public key to secret?

### ISSUE THREAD

**Issue by gamesguru** [sphincs/pyspx#3]
Is there any reason the secret key has the public key stuck on the end?  It looks like 64 + 64 = 128 characters?

I can handle it on my client side, i was just curious why.  Thanks.

**Comment by cryptojedi** [comment]
gamesguru <notifications@github.com> wrote:

> Is there any reason the secret key has the public key stuck on the
> end?  It looks like 64 + 64 = 128 characters?  I can handle it on my
> client side, i was just curious why.  Thanks.

It's attached because the public key is used also during signing,
specifically to compute

  (MD||idx) = H_msg(R, PK.seed, PK.root, M).

See http://sphincs.org/data/sphincs+-paper.pdf, Section 3.5.
