### ISSUE TITLE
proposal to update README.md

### ISSUE THREAD

**Issue by illucent** [sphincs/pyspx#5]
NameError: name 'seed' is not defined
NameError: name 'sphincs' is not defined

```
import pyspx.shake256_128f as sphincs
import os, binascii

# Key generation: private + public key
seed = os.urandom(sphincs.crypto_sign_SEEDBYTES)
```
as in [here](https://github.com/nakov/Practical-Cryptography-for-Developers-Book/blob/3cbe60554b9a1fce016a41fce708525adcd0323f/quantum-safe-cryptography/quantum-safe-signatures-example.md)

**Comment by rugo** [comment]
Don't know what you are trying to tell me.
